version: '3.4'
services:
  app:
    build: 
      context: .
      target: covid_most_base
      dockerfile: ./.docker/development/Dockerfile
    image: covid_most:dev-0.0.1
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/covid_most:cached
      - rails_cache:/covid_most/tmp/cache
      - bundle:/bundle
      - node_modules:/covid_most/node_modules
      - packs:/covid_most/public/packs
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_DATABASE=covid_most_development
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_local
      - DB_HOST=db
      - DB_PORT=5432
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIA123456789}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-AbcD987654321}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_ROOT_NAMESPACE=${AWS_S3_ROOT_NAMESPACE:-root_bucket}
      - AWS_BUCKET_ROOT_NAMESPACE=${AWS_BUCKET_ROOT_NAMESPACE:-root_bucket}
      - AWS_CONNECT_INSTANCE_ID=${AWS_CONNECT_INSTANCE_ID:-123456789}
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=covid_most_development
      - POSTGRES_PASSWORD=postgres_local
volumes:
  pgdata: 
  rails_cache:
  bundle:
  node_modules:
  packs:
