---
registry:
  - namespace:
      - :features
    features:
      - key: :covid_most
        is_enabled: true
        meta: 
          label: Covid Most
          type: :boolean
          default: true
          value: true
          description: Application for contact tracing
          is_required: true
          is_visible: true
        settings:
          - key: :copyright_period_start
            item: "2013"
          - key: :policies_url
            item: "https://dchealthlink.com/"         
          - key: :faqs_url
            item: "https://www.dchealthlink.com/Frequently-Asked-Questions"   
          - key: :help_url
            item: "https://www.dchealthlink.com/help"
