---
registry:
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    features:
      - key: :contribution_model_aca_shop
        item: BenefitMarkets::Operations::ContributionModels::Create.new
        is_enabled: true
      - key: :assign_contribution_model_aca_shop
        item: BenefitMarkets::Operations::ContributionModels::Assign.new
        is_enabled: true
# ---
# registry:
#   features:
#     - key: :covid_most
#       settings:
#         - key:
#           item:
#         - key:
#           item:s
#   - namespace:
#       - :covid_most 
#     features:
#       - key: :call_center
#         is_enabled: true
#         settings:
#           - key: :
#             item: "2013"