---
registry:
  - namespace:
    - :system
    - :services
    - :aws
    features:
      - key: :boot
        item: Services::Start.new
        is_enabled: true
        settings:
        - key: :services
          item:
          - :smtp_service
          - :call_center
          - :doc_store
          - :sns_service
        - key: :start
          item: 'operations/services/start'
        - key: :stop
          item: 'operations/services/stop'
        - key: :restart
          item: 'operations/services/restart'
      # - key: :smtp_service_connection
      #   item: 'operations/smtp_service/connect'
      #   is_enabled: true
      # - key: sms_service_connection
      #   item: 'operations/sms_service/connect'
      #   is_enabled: true
      #   settings:
      #     - key:  # key/value pairs needed to establish connection
      #       value:
      # - key: doc_store_connection
        # item: 'operations/doc_store/connect'
        # is_enabled: true
        # settings:  # key/value pairs needed to establish connection
        #   - key: :root
        #     value: "bucket_name"  # 
        #     key: :s3_id
        #     value: "lksdflj"
      # - key: :call_center
      #   item: 'call_center/operations/client/create'
      #   is_enabled: true
      #   settings:
      #   - key: :login_url
      #     item: "https://demo-covid.awsapps.com/connect/login"
      #   - key: :instance_id
      #     item: "a532ev33r"
      #   - key: :call_recordings
      #     item: "covidmost/connect/demo-covid/CallRecordings"
      #   - key: :chat_transcripts
      #     item: "covidmost/connect/demo-covid/ChatTranscripts"
      #   - key: :exported_reports
      #     item: "covidmost/connect/demo-covid/Reports"
      # - key: :call_center_client
      #   item: 'operations/call_center/connect'
      #   is_enabled: true
      #   settings:
      #   - key: :connect_instance_url
      #     item: "https://demo-covid.awsapps.com/connect/ccp#"
      #   - key: :login_popup
      #     item: true
      #   - key: :softphone_allow_framed
      #     item: true
      #   - key: :softphone_disable_ringtone
      #     item: false
      #   - key: :softphone_ringtone_url
      #     item: "./ringtone.mp3"
